version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - npm install --prefix ./backend
      - npx prisma generate
  build:
    commands:
      - npm run build --prefix ./backend
artifacts:
  files:
    - '**/*'
  base-directory: './backend'
