version: 0.2

phases:
#  install:
#    runtime-versions:
#      java: corretto11
  pre_build:
    commands:
      - npm install --prefix ./backend
  build:
    commands:
      - npm run build --prefix ./backend
artifacts:
  files:
    - '**/*'
  base-directory: './backend/dist'
